"""
Energy-Based Transformer (EBT) actor for wind farm control.

Replaces the diffusion actor with an explicit Energy-Based Model that directly
outputs E(s, a) as a scalar energy value. Actions are generated by gradient
descent on this energy landscape, and composed energies enable post-hoc safety
constraints without retraining.

Key differences from the diffusion actor:
    - EXPLICIT energy: outputs E(s,a) scalar, not noise prediction
    - Gradient descent sampling: no DDPM/DDIM, no noise schedules
    - Self-verification: generate M candidates, pick lowest energy
    - Exact composition: E_total = E_actor + λ·E_load (not classifier guidance)

References:
    - Gladstone et al. 2025, "Energy-Based Transformers are Scalable Learners
      and Thinkers" (EBT)
    - Du & Mordatch 2019, "Implicit Generation and Modeling with Energy Based
      Models" (optimization-based EBM training)
"""

import json
from typing import Optional, Tuple, List, Callable

import torch
import torch.nn as nn

from config import Args
from networks import (
    TransformerEncoder,
    create_positional_encoding,
    create_profile_encoding,
)


# =============================================================================
# ENERGY MLP
# =============================================================================

class EnergyMLP(nn.Module):
    """
    Per-turbine energy scorer. Shared weights across turbines.

    Takes (turbine_embedding, candidate_action) and outputs a scalar energy
    per turbine. Lower energy = higher compatibility / better action.
    """

    def __init__(
        self,
        embed_dim: int,
        action_dim: int,
        hidden_dim: int = 256,
        num_layers: int = 3,
    ):
        super().__init__()
        input_dim = embed_dim + action_dim
        layers: list[nn.Module] = []
        for i in range(num_layers):
            in_d = input_dim if i == 0 else hidden_dim
            layers.append(nn.Linear(in_d, hidden_dim))
            layers.append(nn.ReLU())
        # Output: scalar energy per turbine (no activation — energy is unbounded)
        layers.append(nn.Linear(hidden_dim, 1))
        self.net = nn.Sequential(*layers)

    def forward(
        self,
        turbine_emb: torch.Tensor,
        action: torch.Tensor,
    ) -> torch.Tensor:
        """
        Args:
            turbine_emb: (batch, n_turbines, embed_dim)
            action: (batch, n_turbines, action_dim)

        Returns:
            (batch, n_turbines, 1) scalar energy per turbine
        """
        x = torch.cat([turbine_emb, action], dim=-1)
        return self.net(x)


# =============================================================================
# EBT ACTOR
# =============================================================================

class TransformerEBTActor(nn.Module):
    """
    Transformer-based Energy-Based Model actor for wind farm control.

    Architecture is identical to TransformerActor / TransformerDiffusionActor
    up to the transformer encoder. The action head is an EnergyMLP that scores
    (state, action) pairs, and actions are generated by gradient descent on
    this energy landscape.

    At inference, self-verification generates M candidates and picks the one
    with lowest energy. Composition with load/safety energies is exact addition.
    """

    def __init__(
        self,
        obs_dim_per_turbine: int,
        action_dim_per_turbine: int = 1,
        embed_dim: int = 128,
        pos_embed_dim: int = 32,
        num_heads: int = 4,
        num_layers: int = 2,
        mlp_ratio: float = 2.0,
        dropout: float = 0.0,
        action_scale: float = 1.0,
        action_bias: float = 0.0,
        # Positional encoding settings
        pos_encoding_type: str = "absolute_mlp",
        rel_pos_hidden_dim: int = 64,
        rel_pos_per_head: bool = True,
        pos_embedding_mode: str = "concat",
        # Profile encoding settings
        profile_encoding: Optional[str] = None,
        profile_encoder_hidden: int = 128,
        n_profile_directions: int = 360,
        profile_fusion_type: str = "add",
        profile_embed_mode: str = "add",
        # Shared profile encoders
        shared_recep_encoder: Optional[nn.Module] = None,
        shared_influence_encoder: Optional[nn.Module] = None,
        args: Optional[Args] = None,
        # EBT-specific settings
        energy_hidden_dim: int = 256,
        energy_num_layers: int = 3,
        opt_steps_train: int = 3,
        opt_steps_eval: int = 10,
        opt_lr: float = 0.1,
        num_candidates: int = 8,
        langevin_noise: float = 0.01,
        random_steps: bool = True,
        random_lr: bool = True,
    ):
        super().__init__()

        self.obs_dim_per_turbine = obs_dim_per_turbine
        self.action_dim_per_turbine = action_dim_per_turbine
        self.embed_dim = embed_dim
        self.pos_encoding_type = pos_encoding_type

        self.profile_encoding = profile_encoding
        self.profile_fusion_type = profile_fusion_type
        self.profile_embed_mode = profile_embed_mode

        # EBT optimization settings
        self.opt_steps_train = opt_steps_train
        self.opt_steps_eval = opt_steps_eval
        self.opt_lr = opt_lr
        self.num_candidates = num_candidates
        self.langevin_noise = langevin_noise
        self.random_steps = random_steps
        self.random_lr = random_lr

        assert profile_fusion_type in ("add", "joint")
        assert profile_embed_mode in ("add", "concat")

        # === Positional encoding (identical to TransformerActor) ===
        self.pos_encoder, self.rel_pos_bias, self.embedding_mode = \
            create_positional_encoding(
                encoding_type=pos_encoding_type,
                embed_dim=embed_dim,
                pos_embed_dim=pos_embed_dim,
                num_heads=num_heads,
                rel_pos_hidden_dim=rel_pos_hidden_dim,
                rel_pos_per_head=rel_pos_per_head,
                embedding_mode=pos_embedding_mode,
            )

        # === Profile encoding (identical to TransformerActor) ===
        if shared_recep_encoder is not None and shared_influence_encoder is not None:
            self.recep_encoder = shared_recep_encoder
            self.influence_encoder = shared_influence_encoder
        else:
            encoder_kwargs = json.loads(args.profile_encoder_kwargs) if args else {}
            self.recep_encoder, self.influence_encoder = \
                create_profile_encoding(
                    profile_type=profile_encoding,
                    embed_dim=embed_dim,
                    hidden_channels=profile_encoder_hidden,
                    **encoder_kwargs,
                )

        if profile_encoding is not None and profile_fusion_type == "joint":
            self.profile_fusion = nn.Linear(2 * embed_dim, embed_dim)

        if profile_encoding is not None and profile_embed_mode == "concat":
            self.profile_proj = nn.Linear(2 * embed_dim, embed_dim)

        # === Observation encoder (identical to TransformerActor) ===
        self.obs_encoder = nn.Sequential(
            nn.Linear(obs_dim_per_turbine, embed_dim),
            nn.ReLU(),
            nn.Linear(embed_dim, embed_dim),
        )

        # === Input projection (identical to TransformerActor) ===
        if self.embedding_mode == "concat":
            self.input_proj = nn.Linear(embed_dim + pos_embed_dim, embed_dim)
        else:
            self.input_proj = nn.Identity()

        # === Transformer encoder (identical to TransformerActor) ===
        self.transformer = TransformerEncoder(
            embed_dim, num_heads, num_layers, mlp_ratio, dropout
        )

        # === EBT-specific: Energy head ===
        self.energy_head = EnergyMLP(
            embed_dim=embed_dim,
            action_dim=action_dim_per_turbine,
            hidden_dim=energy_hidden_dim,
            num_layers=energy_num_layers,
        )

        # Action scaling (identical to TransformerActor)
        self.register_buffer("action_scale", torch.tensor(action_scale, dtype=torch.float32))
        self.register_buffer("action_bias_val", torch.tensor(action_bias, dtype=torch.float32))

    # -----------------------------------------------------------------
    # Encoder (shared structure with other actors)
    # -----------------------------------------------------------------

    def encode(
        self,
        obs: torch.Tensor,
        positions: torch.Tensor,
        key_padding_mask: Optional[torch.Tensor] = None,
        recep_profile: Optional[torch.Tensor] = None,
        influence_profile: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """
        Run transformer encoder, return per-turbine embeddings.

        Factored out so embeddings are computed once and reused
        across all optimization steps.

        Returns:
            h: (batch, n_turbines, embed_dim)
        """
        h = self.obs_encoder(obs)

        if self.embedding_mode == "concat" and self.pos_encoder is not None:
            pos_embed = self.pos_encoder(positions)
            h = torch.cat([h, pos_embed], dim=-1)
        elif self.embedding_mode == "add" and self.pos_encoder is not None:
            pos_embed = self.pos_encoder(positions)
            h = h + pos_embed

        h = self.input_proj(h)

        if self.recep_encoder and recep_profile is not None and influence_profile is not None:
            recep_embed = self.recep_encoder(recep_profile)
            influence_embed = self.influence_encoder(influence_profile)
            if self.profile_fusion_type == "joint":
                profile_embed = self.profile_fusion(
                    torch.cat([recep_embed, influence_embed], dim=-1)
                )
            else:
                profile_embed = recep_embed + influence_embed

            if self.profile_embed_mode == "concat":
                h = self.profile_proj(torch.cat([h, profile_embed], dim=-1))
            else:
                h = h + profile_embed

        attn_bias = None
        if self.rel_pos_bias is not None:
            attn_bias = self.rel_pos_bias(positions, key_padding_mask)

        h, _ = self.transformer(h, key_padding_mask, attn_bias, need_weights=False)
        return h

    # -----------------------------------------------------------------
    # Energy computation
    # -----------------------------------------------------------------

    def compute_energy(
        self,
        turbine_emb: torch.Tensor,
        action: torch.Tensor,
        key_padding_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """
        Compute scalar energy E(s, a) for a batch of state-action pairs.

        Args:
            turbine_emb: (batch, n_turbines, embed_dim)
            action: (batch, n_turbines, action_dim) in [-1, 1] normalized space
            key_padding_mask: (batch, n_turbines) True = padding

        Returns:
            (batch, 1) scalar energy per batch element
        """
        energy_per_turbine = self.energy_head(turbine_emb, action)  # (batch, n_turb, 1)
        if key_padding_mask is not None:
            mask = (~key_padding_mask).unsqueeze(-1).float()
            energy_per_turbine = energy_per_turbine * mask
            energy = energy_per_turbine.sum(dim=1) / mask.sum(dim=1).clamp(min=1)
        else:
            energy = energy_per_turbine.mean(dim=1)
        return energy  # (batch, 1)

    # -----------------------------------------------------------------
    # Action optimization (core EBT mechanism)
    # -----------------------------------------------------------------

    def _compose_per_turbine_energy(
        self,
        emb: torch.Tensor,
        actions: torch.Tensor,
        mask_expanded: Optional[torch.Tensor],
        extra_energy_fns: List[Tuple[Callable, float]],
    ) -> torch.Tensor:
        """
        Compose actor energy with constraint energies at the per-turbine level,
        then aggregate to a scalar.

        Returns:
            (batch, 1) scalar energy after per-turbine composition and masked mean.
        """
        # Per-turbine actor energy (batch, n_turb, 1)
        energy_per_turb = self.energy_head(emb, actions)

        # Per-turbine composition: add constraint energies before aggregation
        for energy_fn, weight in extra_energy_fns:
            action_scaled = actions * self.action_scale + self.action_bias_val
            energy_per_turb = energy_per_turb + weight * energy_fn(action_scaled, mask_expanded)

        # Aggregate: masked mean over turbines
        if mask_expanded is not None:
            mask_float = (~mask_expanded).unsqueeze(-1).float()
            energy_per_turb = energy_per_turb * mask_float
            energy = energy_per_turb.sum(dim=1) / mask_float.sum(dim=1).clamp(min=1)
        else:
            energy = energy_per_turb.mean(dim=1)

        return energy  # (batch, 1)

    def optimize_actions(
        self,
        turbine_emb: torch.Tensor,
        key_padding_mask: Optional[torch.Tensor] = None,
        num_steps: Optional[int] = None,
        num_candidates: int = 1,
        extra_energy_fns: Optional[List[Tuple[Callable, float]]] = None,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Generate actions via gradient descent on the energy landscape.

        Energy composition happens per-turbine: each turbine sees its own
        constraint penalty before aggregation. This ensures turbine-specific
        constraint gradients are not diluted.

        During training: create_graph=True so gradients flow back through
        the optimization chain into the energy head (Hessian-vector products).

        During inference: generate M candidates and pick lowest energy
        (self-verification).

        Args:
            turbine_emb: (batch, n_turbines, embed_dim)
            key_padding_mask: (batch, n_turbines) True = padding
            num_steps: override optimization steps (default: train/eval setting)
            num_candidates: M candidates for self-verification
            extra_energy_fns: list of (fn, weight) for per-turbine energy composition.
                fn must return (batch, n_turbines, 1) per-turbine energies.

        Returns:
            best_actions: (batch, n_turbines, action_dim) in [-1, 1]
            best_energies: (batch, 1) energy of selected actions
        """
        if extra_energy_fns is None:
            extra_energy_fns = []

        batch, n_turb, _ = turbine_emb.shape
        device = turbine_emb.device

        if num_steps is None:
            num_steps = self.opt_steps_train if self.training else self.opt_steps_eval

        # --- Regularization: randomize steps and lr (EBT Section 3.3) ---
        if self.training and self.random_steps:
            num_steps = int(torch.randint(max(1, num_steps // 2), num_steps + 1, (1,)).item())
        lr = self.opt_lr
        if self.training and self.random_lr:
            lr = lr * (0.5 + float(torch.rand(1, device=device).item()))

        # --- Expand for M candidates ---
        if num_candidates > 1:
            emb = turbine_emb.repeat(num_candidates, 1, 1)
            mask_expanded = key_padding_mask.repeat(num_candidates, 1) if key_padding_mask is not None else None
        else:
            emb = turbine_emb
            mask_expanded = key_padding_mask

        # Padding mask for zeroing
        pad_float = None
        if mask_expanded is not None:
            pad_float = (~mask_expanded).unsqueeze(-1).float()

        # --- Initialize candidates ---
        actions = torch.randn(
            batch * num_candidates, n_turb, self.action_dim_per_turbine, device=device
        )
        actions = actions.clamp(-1.0, 1.0)
        if pad_float is not None:
            actions = actions * pad_float

        # --- Optimization loop ---
        # enable_grad is needed because callers (agent.act) use torch.no_grad(),
        # but we always need gradients for energy-based optimization.
        with torch.enable_grad():
            for _ in range(num_steps):
                actions = actions.detach().requires_grad_(True)

                # Per-turbine composition then aggregate
                energy = self._compose_per_turbine_energy(
                    emb, actions, mask_expanded, extra_energy_fns
                )

                # Gradient descent step
                grad = torch.autograd.grad(
                    energy.sum(), actions, create_graph=self.training
                )[0]
                actions = actions - lr * grad

                # Langevin noise for exploration (training only)
                if self.training and self.langevin_noise > 0:
                    actions = actions + self.langevin_noise * torch.randn_like(actions)

                # Project back to valid range and zero padding
                actions = actions.clamp(-1.0, 1.0)
                if pad_float is not None:
                    actions = actions * pad_float

        # --- Self-verification: pick lowest energy candidate ---
        if num_candidates > 1:
            with torch.no_grad():
                final_energy = self._compose_per_turbine_energy(
                    emb, actions, mask_expanded, extra_energy_fns
                )

                # Reshape: (num_candidates, batch, ...)
                final_energy = final_energy.view(num_candidates, batch, 1)
                actions_reshaped = actions.view(num_candidates, batch, n_turb, self.action_dim_per_turbine)

                # Select best candidate per batch element
                best_idx = final_energy.argmin(dim=0)  # (batch, 1)
                # Gather best actions: index into candidate dimension
                best_idx_expanded = best_idx.unsqueeze(-1).expand(-1, -1, self.action_dim_per_turbine)  # (batch, 1, action_dim)
                best_idx_expanded = best_idx_expanded.unsqueeze(1).expand(-1, n_turb, -1, -1)  # (batch, n_turb, 1, action_dim)
                # Simpler: use a loop-free gather
                best_idx_a = best_idx.view(1, batch, 1, 1).expand(1, batch, n_turb, self.action_dim_per_turbine)
                best_actions = actions_reshaped.gather(0, best_idx_a).squeeze(0)  # (batch, n_turb, action_dim)
                best_energies = final_energy.gather(0, best_idx.unsqueeze(0)).squeeze(0)  # (batch, 1)
        else:
            best_actions = actions
            with torch.no_grad():
                best_energies = self.compute_energy(
                    turbine_emb, actions, key_padding_mask
                )

        return best_actions, best_energies

    # -----------------------------------------------------------------
    # Action interface (drop-in replacement for TransformerActor)
    # -----------------------------------------------------------------

    def get_action(
        self,
        obs: torch.Tensor,
        positions: torch.Tensor,
        key_padding_mask: Optional[torch.Tensor] = None,
        deterministic: bool = False,
        recep_profile: Optional[torch.Tensor] = None,
        influence_profile: Optional[torch.Tensor] = None,
        need_weights: bool = False,
        guidance_fn: Optional[Callable] = None,
        guidance_scale: float = 0.0,
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, List[torch.Tensor]]:
        """
        Generate action via energy minimization.

        Drop-in replacement for TransformerActor.get_action(). Returns the same
        tuple format: (action, log_prob, mean_action, attn_weights).

        log_prob is set to -energy (unnormalized log-probability from the EBM).
        """
        turbine_emb = self.encode(
            obs, positions, key_padding_mask, recep_profile, influence_profile
        )

        # Build extra energy functions for per-turbine composition.
        # If the guidance_fn has a per_turbine_energy method, use it;
        # otherwise fall back to the callable directly.
        extra_energy_fns: List[Tuple[Callable, float]] = []
        if guidance_fn is not None and guidance_scale > 0:
            if hasattr(guidance_fn, 'per_turbine_energy'):
                extra_energy_fns.append((guidance_fn.per_turbine_energy, guidance_scale))
            else:
                extra_energy_fns.append((guidance_fn, guidance_scale))

        # More candidates at eval for self-verification
        num_candidates = self.num_candidates if not self.training else 1

        actions, energies = self.optimize_actions(
            turbine_emb,
            key_padding_mask,
            num_candidates=num_candidates,
            extra_energy_fns=extra_energy_fns,
        )

        # Scale to action space
        action_scaled = actions * self.action_scale + self.action_bias_val

        # Energy as unnormalized log-prob (lower energy = higher probability)
        log_prob = -energies  # (batch, 1)

        mean_action = action_scaled
        attn_weights: List[torch.Tensor] = []

        return action_scaled, log_prob, mean_action, attn_weights
